### ISSUE TITLE
vinyl: truncate does not work

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#1435]
```
box.space.garage_infos:truncate()                                                      
—-                                                                                    
- error: phia/environment/se_conf.c:490 database has been scheduled for shutdown/drop
```

**Comment by rtsisyk** [comment]
Already fixed by #1452
```
tarantool> box.schema.space.create('test', { engine = 'phia' })
tarantool> box.space.test:create_index('primary')

tarantool> box.space.test:truncate()
---
...
```
Need a test case.

**Comment by pgulutzan** [comment]
It is not fixed. Although it works okay in the simple test case above, there is a way to make it fail -- and destroy the primary index. I am using Tarantool 1.7, pulled from source today. Try:
box.schema.space.create('t5',{engine='vinyl'})
box.space.t5:create_index('primary')
box.space.t5:insert{44}
box.space.t5:truncate()
box.space.t5:insert{55}
Notice that the first insert succeeds, then the truncate fails, then the second insert fails.

**Comment by rtsisyk** [comment]
This problem is still actual:
```
tarantool> box.schema.space.create('vinyl',{engine='vinyl'})
tarantool> box.space.vinyl:create_index('primary')
---
- unique: true
  parts:
  - type: NUM
    fieldno: 1
  id: 0
  space_id: 512
  name: primary
  type: TREE
...

tarantool> box.space.vinyl:insert({1, 2})
---
...

tarantool> box.space.vinyl:truncate()
---
- error: 'index file ''./512:0/00000000000000000000.00000000000000000002.index.incomplete''
    unlink error: No such file or directory'
...
```

**Comment by Gerold103** [comment]
After fixing this issue, please, don't forgot to move tests on truncate from box/lua.test.lua to engine/lua.test.lua.
