### ISSUE TITLE
Exit from interactive session by ^D instead of ^C

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1510]
Many interactive interpreters will exit only when you type ^D. By pressing ^C you just interrupt current executing command or get a "new clean line". 

Currently the interactive session will exit on ^C, which may be frustrating for many users, as the command is in muscle memory. I personally stumbled upon this many times, but I'm just unable to "unlearn" this behavior of ^C/^D

**Comment by hengestone** [comment]
Agreed, ^C should cancel the current input line (interrupt) and ^D should exit (end of stream). I keep exiting too ;-)

**Comment by rtsisyk** [comment]
```
psql
psql (9.5.3)
Type "help" for help.

postgres=# SELECT 1;
 ?column? 
----------
        1
(1 row)

postgres=# ^C
postgres=# ^C
postgres=# ^C
postgres=# /q <!-- ^D
```

```
Python 2.7.11+ (default, May  9 2016, 15:54:33) 
[GCC 5.3.1 20160429] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1+1
2
>>> 
KeyboardInterrupt
>>> <!-- ^D
```

```
$ nodejs
> 1+1
2
> 
(To exit, press ^C again or type .exit)
```

```
 swift
Welcome to Swift version 3.0-dev (LLVM 752e1430fc, Clang 3987718dae, Swift 36739f7b57). Type :help for assistance.
  1> 1+1
$R0: Int = 2
  2> ^C
  2> ^C
  2> ^D
```

**Comment by pgulutzan** [comment]
A similar complaint re MySQL's command-line client https://bugs.mysql.com/bug.php?id=66583 was followed by a change, but not in MariaDB.

**Comment by kostja** [comment]
Haven't we done it?

**Comment by rtsisyk** [comment]
Fixed in 1.7.1-1-gb4a4139

**Comment by pgulutzan** [comment]
Now in version 1.7 ^D stops both server in interactive mode, and tarantoolctl connect. I see that ^C does the same thing, its behaviour is unchanged. I'll assume this is intentional, although it doesn't exactly match the issue description.

**Comment by kostja** [comment]
* Peter Gulutzan <notifications@github.com> [16/07/13 19:17]:
> Now in version 1.7 ^D stops both server in interactive mode, and
> tarantoolctl connect. I see that ^C does the same thing, its
> behaviour is unchanged. I'll assume this is intentional,
> although it doesn't exactly match the issue description.

Oops. We didn't fix this bug, nothing should have changed from
1.6.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
rolling feature => 1.7.3

**Comment by rtsisyk** [comment]
I suggest to move to 1.7.4

**Comment by rtsisyk** [comment]
I don't have any ideas how to implement this feature, moved to 1.7.4
