### ISSUE TITLE
Only allow identifiers which are valid in Tarantool.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2126]
Tarantool doesn't support special characters in identifiers, so let's do the same in SQL.

>I am able to say
create table ЯЯ$ (s1 int, primary key (s1));
but later I am not able to say
box.space.ЯЯ$:select{}
In other words, valid names in SQLite are not the
same as valid names in Tarantool. Of course, the
Tarantool code could be changed to allow more
characters, such as '$'. But I expect it will be
decided that it's simpler to say: a name is not
valid in SQL if it is not valid in Tarantool.
This applies to both regular and delimited identifiers.
(In delimited identifiers special characters should
be allowed, but that doesn't have to be true in
Tarantool-SQL immediately.)

**Comment by mejedi** [comment]
Right now the example yields
```
tarantool> box.sql.execute('create table ЯЯ$ (s1 int, primary key (s1));')
---
- error: Invalid identifier 'ЯЯ$' (expected letters, digits or an underscore)
...
```

Fixed?

**Comment by kyukhin** [comment]
This is still an issue. `sqlite-tcl/quote.test-1.0` fails because we do not support delimited identifiers.

**Comment by kyukhin** [comment]
Here's what I think we should do:
  1. All delimited identifiers are specified using <doulbe quote> symbol (")
  2. All string literals are specified using <quote> symbol (')
  3. Any other quotation is prohibited
  4. Maximal length of identifier is limited to 64KB
  5. Rules for all identifiers are the same.
     This is not a limitation, ANSI says so, e.g. for table and columns names
        <table name> ::= <local or schema qualified name>
        <local or schema qualified name> ::=
        [ <local or schema qualifier> <period> ] <qualified identifier>
        <qualified identifier> ::= <identifier>
        <column name> ::= <identifier>
  6. We will allow to use UTF-8 identifiers: only delimited (I see only
     <Unicode delimited identifier> in the standard). Comparison of
     such identifiers will be done using libICU facilities
  7. We will support UESCAPE, with lower prio though
  8. All keywords mentioned in Chapter 5.2 ("<token> and <separator>") cannot
     be used as identifiers, both delimited and regular
  9. In future, we'll consider support of array non-scalar type. To specify
     it, square brackets (<left|right bracket>, [ ]) as well as left, right
     bracket trigraphs (<left|right bracket trigraph>, ??( )??) will be used

**Comment by Khatskevich** [comment]
I have made some refactoring on Kirills comment:

### Identifier validation as in tarantool:
Identifiers in tarantool allow only [a-Z0-9_], SQL identifiers should follow the same rules so that identifiers can be easily used from Lua.
Here are some points that should be considered:
- [x] table names as in tarantool
- [x] index names as in tarantool
- [ ] ? column names as in tarantool (it do not work in tarantool itself #2914) I suppose this point could be solved automatically after SQL starts using formats.
- [ ] ? virtual tables. Should its names have the same constraints? Cause it is not accessible from tarantool.
- [ ] ? collation names, aliases, and other identifiers. Should they also follow these rules?

#### There are two possible solutions:
1. Validate every identifier with the same function as in Tarantool, but in SQL ( solve all issues mentioned above)
2. Do not validate identifiers in SQL, start use formats (solve issues 1-3)

### Extra issues:

- [x] All delimited identifiers are specified using symbol (")
- [x] All string literals are specified using symbol (')
- [x] Any other quotation is prohibited
- [x] +- true Rules for all identifiers are the same.
- [x] All keywords mentioned in Chapter 5.2 (" and ") cannot
be used as identifiers, both delimited and regular
- [ ] Maximal length of identifier is limited to 64KB (what for? check needed)

### Some clarification needed:
- [ ] **We will allow using UTF-8 identifiers: only delimited (I see only
in the standard). Comparison of
such identifiers will be done using libICU facilities**
1. Why should they be delimited? 
2. For now, they should not be delimited. For now, the uppercase function is not applied for non-ASCII.
3. If as you say we allow use non-ASCII only delimited, then they should be compared case-sensitive and ICU is not necessary (only for a limited number of cases, but should we sacrifice performance for it?)
- [ ] **We will support UESCAPE, with lower priority though**
1. What does it mean?
