### ISSUE TITLE
sql: unify stat table

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#2843]
To gather statistics optimizer uses sql_stat1 and sql_stat4 tables. In original SQLite code only stat1 table is active by default. sql_stat2/3/4 tables can be activated using compiler options. The proposal is to remove useless code for stat2 and stat3 tables. Moreover, executing select query leads to inspection of stat1 and stat4 tables. stat4 contains a way more information about indexes and tables(histogram data), so it could be profitable to unite stat1 and stat4 in one table in order to avoid excess select queries to stat1 table and decline time spending on analyze.

**Comment by kyukhin** [comment]
Done.

**Comment by ImeevMA** [comment]
In the end, it was decided to completely rewrite the logic of the ANALYZE statement. Until this was done, the following tests were disabled in #4069:
sql-tap/analyze1.test.lua
sql-tap/analyze3.test.lua
sql-tap/analyze4.test.lua
sql-tap/analyze5.test.lua
sql-tap/analyze6.test.lua
sql-tap/analyze7.test.lua
sql-tap/analyze8.test.lua
sql-tap/analyze9.test.lua
sql-tap/analyzeC.test.lua
sql-tap/analyzeD.test.lua
sql-tap/analyzeE.test.lua
sql-tap/analyzeF.test.lua

And these were partially commented:
sql/row-count.test.lua
sql/triggers.test.lua

**Comment by Korablev77** [comment]
You missed test/sql-tap/whereG.test.lua and  test/sql-tap/gh-3350-skip-scan.test.lua - they contain several commented tests now.

**Comment by igormunkin** [comment]
There are no `_sql_stat2` and `_sql_stat3` spaces since 1.8.2-287-g9dcc529a9 (9dcc529); `_sql_stat1` and  `_sql_stat4` spaces are removed since 2.2.0-108-gec93b4a5 (ec93b4a).
