### ISSUE TITLE
Segmentation fault: json.encode recursive table

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4366]
### Tarantool version

2.2.0-568-gc185a3872

### Bug description:

Segmentation fault (stack overflow)

### Steps to reproduce

```lua
json = require('json')
tbl = {}
tbl[1] = tbl
json.encode(tbl)
```

### Backtrace

```
#0  0x00005555556b8aab in lua_getmetatable ()
#1  0x00005555556b8b52 in luaL_getmetafield ()
#2  0x000055555566fa85 in lua_field_try_serialize (L=0x40000378) at /opt/tntsrc/src/lua/utils.c:480
#3  0x00005555556a7857 in lj_BC_FUNCC ()
#4  0x00005555556b93e4 in lua_pcall ()
#5  0x000055555566f426 in lua_field_inspect_table (field=0x7fffed902190, idx=3578, cfg=0x400173b8, L=0x40000378) at /opt/tntsrc/src/lua/utils.c:539
#6  luaL_tofield (L=L@entry=0x40000378, cfg=cfg@entry=0x400173b8, index=3578, index@entry=-1, field=field@entry=0x7fffed902190) at /opt/tntsrc/src/lua/utils.c:744
#7  0x000055555567e7fb in luaL_checkfield (field=0x7fffed902190, idx=-1, cfg=0x400173b8, L=0x40000378) at /opt/tntsrc/src/lua/utils.h:374
#8  json_append_data (l=l@entry=0x40000378, cfg=cfg@entry=0x400173b8, current_depth=current_depth@entry=0, json=0x555555b7a120 <encode_buf>)
    at /opt/tntsrc/third_party/lua-cjson/lua_cjson.c:380
#9  0x000055555567e9e4 in json_append_array (json=0x555555b7a120 <encode_buf>, array_length=1, current_depth=0, cfg=0x400173b8, l=0x40000378)
    at /opt/tntsrc/third_party/lua-cjson/lua_cjson.c:283
#10 json_append_data (l=l@entry=0x40000378, cfg=cfg@entry=0x400173b8, current_depth=current_depth@entry=0, json=0x555555b7a120 <encode_buf>)
    at /opt/tntsrc/third_party/lua-cjson/lua_cjson.c:411
#11 0x000055555567e9e4 in json_append_array (json=0x555555b7a120 <encode_buf>, array_length=1, current_depth=0, cfg=0x400173b8, l=0x40000378)
    at /opt/tntsrc/third_party/lua-cjson/lua_cjson.c:283
#12 json_append_data (l=l@entry=0x40000378, cfg=cfg@entry=0x400173b8, current_depth=current_depth@entry=0, json=0x555555b7a120 <encode_buf>)
    at /opt/tntsrc/third_party/lua-cjson/lua_cjson.c:411

then it repeats
```

### Note

Recursive table with string keys works a little bit better, but still dangerous:

```lua
tbl = {}
tbl['x'] = tbl
print(json.encode(tbl))
-- produces the following: (depth 32)
-- {"x":{"x":{"x":{"x":{"x":{"x":{"x":{"x":
-- {"x":{"x":{"x":{"x":{"x":{"x":{"x":{"x":
-- {"x":{"x":{"x":{"x":{"x":{"x":{"x":{"x":
-- {"x":{"x":{"x":{"x":{"x":{"x":{"x":{"x":null}
-- }}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}
```

```lua
tbl = {}
tbl['x'] = tbl
tbl['y'] = tbl
print(json.encode(tbl))
-- wastes 100% CPU (1 core)
-- hangs for more than 30 sec (I didn't wait more and killed it)
```

**Comment by olegrok** [comment]
Our lua "json" it's fork of "lua_cjson"

However, in the original library the problem is solved.

```lua
tarantool> cjson = require('cjson')
---
...

tarantool> t = {}
---
...

tarantool> t[1] = t
---
...

tarantool> cjson.encode(t)
---
- error: Cannot serialise, excessive nesting (1001)
...

tarantool> json = require('json')
---
...

tarantool> json.encode(t)
[1]    1997 bus error  tarantool
```
https://github.com/mpx/lua-cjson/blob/e8972ac754788d3ef10a57a36016d6c3e85ba20d/lua_cjson.c#L559

**Comment by kshcherbatov** [comment]
Actually this problem is not solved there, as far I've understood: crash in module produce "bus error" instead of crashing Tarantool itself
