### ISSUE TITLE
memtx mvcc allows to read uncommited DDL and sometimes crashes

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5515]
Tarantool version: 2.7.0-29-gb8d3c762b

```lua
-- Setup
box.cfg{memtx_use_mvcc_engine=true, listen=3301}
```

### The first case

```lua
-- first console
fiber = require('fiber')
channel = fiber.channel()
function test1()
    box.begin()
    local s = box.schema.space.create('test')
    s:create_index('pk')
    local ok = channel:get()
    box.session.push(ok)
    box.commit()
end
f = fiber.new(test1)
localhost:3301> f
---
- status: suspended
  name: lua
  id: 138
...
```

```lua
-- The second console
localhost:3301> box.space.test 
---
- engine: memtx
  before_replace: 'function: 0x01076e3718'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x01076e36e0'
  temporary: false
  index:
    0: &0
      unique: true
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 1
      hint: true
      id: 0
      type: TREE
      space_id: 516
      name: pk
    pk: *0
  is_local: false
  enabled: true
  name: test
  id: 516
...

localhost:3301> box.space.test:drop() -- Well
---
- error: Space 'test' does not exist
...
localhost:3301> box.space.test:replace({1, 2, 3}) -- Why?
---
- [1, 2, 3]
...
```

```lua
-- return back to the first console
localhost:3301> channel:put(1)
---
- true
...

localhost:3301> box.space.test 
---
- engine: memtx
  before_replace: 'function: 0x01076e3718'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x01076e36e0'
  temporary: false
  index:
    0: &0
      unique: true
      parts:
      - type: unsigned
        is_nullable: false
        fieldno: 1
      hint: true
      id: 0
      type: TREE
      space_id: 516
      name: pk
    pk: *0
  is_local: false
  enabled: true
  name: test
  id: 516
...

localhost:3301> box.space.test:select()
---
- - [1, 2, 3]
...
```

### The second case
```lua
-- first console
fiber = require('fiber')
channel = fiber.channel()
function test1()
    box.begin()
    local s = box.schema.space.create('test')
    s:create_index('pk')
    local ok = channel:get()
    box.session.push(ok)
    box.rollback()
end
f = fiber.new(test1)
localhost:3301> f
---
- status: suspended
  name: lua
  id: 165
...
```

```lua
-- second console
localhost:3301> box.space.test:select()
---
- []
...

localhost:3301> box.space.test:replace({1, 2, 3})
---
- [1, 2, 3]
...
```

```lua
-- the first console
localhost:3301> channel:put(1)
---
- true
...

localhost:3301> box.space.test -- Seems I lost a tuple
---
- null
...
```

I think it's a buggy behaviour, since I have some access to uncommited DDL and don't have any error after transaction is commited.

Well... Finally, it's failed with assertion
```
tarantool> Assertion failed: (!tuple->is_dirty), function tuple_unref, file /Users/o.babin/Projects/tarantool/src/box/tuple.h, line 1121.
```

```log
Tarantool 2.7.0-29-gb8d3c762b
type 'help' for interactive help
tarantool> box.cfg{memtx_use_mvcc_engine=true, listen=3301}
2020-11-12 20:45:33.951 [32859] main/103/interactive C> Tarantool 2.7.0-29-gb8d3c762b
2020-11-12 20:45:33.952 [32859] main/103/interactive C> log level 5
2020-11-12 20:45:33.952 [32859] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2020-11-12 20:45:33.952 [32859] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2020-11-12 20:45:33.959 [32859] main/103/interactive I> instance uuid efc194a9-2c7c-4449-8ffb-e25dd46b6835
2020-11-12 20:45:33.960 [32859] iproto/101/main I> binary: bound to [::]:3301
2020-11-12 20:45:33.960 [32859] main/103/interactive I> initializing an empty data directory
2020-11-12 20:45:33.994 [32859] main/103/interactive I> assigned id 1 to replica efc194a9-2c7c-4449-8ffb-e25dd46b6835
2020-11-12 20:45:33.994 [32859] main/103/interactive I> cluster uuid 7457f9b4-5fc2-4335-bca6-3aac094fe2b8
2020-11-12 20:45:33.996 [32859] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2020-11-12 20:45:33.997 [32859] snapshot/101/main I> done
2020-11-12 20:45:33.997 [32859] main/103/interactive I> ready to accept requests
2020-11-12 20:45:33.998 [32859] main/103/interactive I> set 'log_level' configuration option to 5
2020-11-12 20:45:33.998 [32859] main/105/checkpoint_daemon I> scheduled next checkpoint for Thu Nov 12 22:24:42 2020
2020-11-12 20:45:33.998 [32859] main/103/interactive I> set 'listen' configuration option to "3301"
2020-11-12 20:45:33.998 [32859] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> fiber = require('fiber')
---
...

tarantool> channel = fiber.channel()
---
...

tarantool> function test1()
         >     box.begin()
         >     local s = box.schema.space.create('test')
         >     s:create_index('pk')
         >     s:replace{1, 2, 3}
         >     channel:get()
         >     local ok, err = pcall(box.commit)
         >     if not ok then
         >         require('log').error(err)
         >     end
         > end
---
...

tarantool> f = fiber.new(test1)
---
...

tarantool> f
---
- status: suspended
  name: lua
  id: 116
...

tarantool> box.space.test:replace({1, 2, 3})
---
- [1, 2, 3]
...

tarantool> 
---
...

tarantool> box.space.test:replace({1, 2, 3})
---
- [1, 2, 3]
...

tarantool> 
---
...

tarantool> channel:put(1)
---
- true
...

tarantool> 
---
...

tarantool> box.space.test:select()
---
- - [1, 2, 3]
...

tarantool> 
---
...

tarantool> 
---
...

tarantool> box.cfg{memtx_use_mvcc_engine=true, listen=3301}
---
...

tarantool> fiber = require('fiber')
---
...

tarantool> channel = fiber.channel()
---
...

tarantool> function test1()
         >     box.begin()
         >     local s = box.schema.space.create('test')
         >     s:create_index('pk')
         >     s:replace{1, 2, 3}
         >     channel:get()
         >     local ok, err = pcall(box.rollback)
         >     if not ok then
         >         require('log').error(err)
         >     end
         > end
---
...

tarantool> f = fiber.new(test1)
---
...

tarantool> 2020-11-12 20:46:46.313 [32859] main/117/lua schema.lua:429 E> ER_SPACE_EXISTS: Space 'test' already exists
box.space.test:replace({1, 2, 3})
---
- [1, 2, 3]
...

tarantool> box.space.test:drop()
---
...

tarantool> 
---
...

tarantool> box.cfg{memtx_use_mvcc_engine=true, listen=3301}
---
...

tarantool> fiber = require('fiber')
---
...

tarantool> channel = fiber.channel()
---
...

tarantool> function test1()
         >     box.begin()
         >     local s = box.schema.space.create('test')
         >     s:create_index('pk')
         >     s:replace{1, 2, 3}
         >     channel:get()
         >     local ok, err = pcall(box.rollback)
         >     if not ok then
         >         require('log').error(err)
         >     end
         > end
---
...

tarantool> f = fiber.new(test1)
---
...

tarantool> box.space.test:replace({1, 2, 3})
---
- [1, 2, 3]
...

tarantool> channel:put(1)
---
- true
...

tarantool> collectgarbage()
Assertion failed: (!tuple->is_dirty), function tuple_unref, file /Users/o.babin/Projects/tarantool/src/box/tuple.h, line 1121.
[1]    32859 abort      ./src/tarantool
```

And I after my experiments I can't bootstrap instance:
```
...
2020-11-12 20:42:53.685 [32424] main/103/interactive I> instance vclock {1: 45}
2020-11-12 20:42:53.687 [32424] iproto/101/main I> binary: bound to [::]:3301
2020-11-12 20:42:53.688 [32424] main/103/interactive I> recovery start
2020-11-12 20:42:53.688 [32424] main/103/interactive I> recovering from `./00000000000000000000.snap'
2020-11-12 20:42:53.706 [32424] main/103/interactive I> cluster uuid 35d45be0-203c-4777-8bec-608327012d2b
2020-11-12 20:42:53.727 [32424] main/103/interactive I> assigned id 1 to replica ec158fe5-a3d6-49f5-b1f4-cdb17742b477
2020-11-12 20:42:53.727 [32424] main/103/interactive I> recover from `./00000000000000000000.xlog'
2020-11-12 20:42:53.728 [32424] main/103/interactive I> done `./00000000000000000000.xlog'
2020-11-12 20:42:53.728 [32424] main/103/interactive I> recover from `./00000000000000000024.xlog'
2020-11-12 20:42:53.728 [32424] main/103/interactive I> done `./00000000000000000024.xlog'
2020-11-12 20:42:53.728 [32424] main/103/interactive I> recover from `./00000000000000000025.xlog'
2020-11-12 20:42:53.728 [32424] main/103/interactive schema.h:84 E> ER_NO_SUCH_SPACE: Space '516' does not exist
2020-11-12 20:42:53.728 [32424] main/103/interactive F> can't initialize storage: Space '516' does not exist
```

**Comment by olegrok** [comment]
100% reproducer

```lua
fiber = require('fiber')
box.cfg{listen = 3301, memtx_use_mvcc_engine=true}
box.begin()
s = box.schema.space.create('test')
box.space.test:create_index('pk')
box.space.test:replace({1,2,3})
f = fiber.new(function() s:replace({2,2,3}) s:replace({3,2,3}) end)
f:set_joinable(true)
f:join()
box.space.test:truncate()
box.rollback()
collectgarbage()
```

```
➜  tarantool git:(master) ✗ ./src/tarantool 
Tarantool 2.7.0-70-g10a1c6090
type 'help' for interactive help
tarantool> fiber = require('fiber')
---
...

tarantool> box.cfg{listen = 3301, memtx_use_mvcc_engine=true}
2020-11-29 12:37:52.826 [68811] main/103/interactive C> Tarantool 2.7.0-70-g10a1c6090
2020-11-29 12:37:52.827 [68811] main/103/interactive C> log level 5
2020-11-29 12:37:52.827 [68811] main/103/interactive I> mapping 268435456 bytes for memtx tuple arena...
2020-11-29 12:37:52.827 [68811] main/103/interactive I> mapping 134217728 bytes for vinyl tuple arena...
2020-11-29 12:37:52.836 [68811] main/103/interactive I> instance uuid d22c4881-1482-41f6-b273-aa67ecd1dfa5
2020-11-29 12:37:52.837 [68811] iproto/101/main I> binary: bound to [::]:3301
2020-11-29 12:37:52.837 [68811] main/103/interactive I> initializing an empty data directory
2020-11-29 12:37:52.869 [68811] main/103/interactive I> assigned id 1 to replica d22c4881-1482-41f6-b273-aa67ecd1dfa5
2020-11-29 12:37:52.869 [68811] main/103/interactive I> cluster uuid a643fc7c-21c0-432a-a75a-0156496fe451
2020-11-29 12:37:52.871 [68811] snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
2020-11-29 12:37:52.872 [68811] snapshot/101/main I> done
2020-11-29 12:37:52.872 [68811] main/103/interactive I> ready to accept requests
2020-11-29 12:37:52.873 [68811] main/103/interactive I> set 'log_level' configuration option to 5
2020-11-29 12:37:52.873 [68811] main/105/checkpoint_daemon I> scheduled next checkpoint for Sun Nov 29 14:09:16 2020
2020-11-29 12:37:52.873 [68811] main/103/interactive I> set 'listen' configuration option to "3301"
2020-11-29 12:37:52.873 [68811] main/103/interactive I> set 'log_format' configuration option to "plain"
---
...

tarantool> box.begin()
---
...

tarantool> s = box.schema.space.create('test')
---
...

tarantool> box.space.test:create_index('pk')
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  hint: true
  id: 0
  type: TREE
  space_id: 512
  name: pk
...

tarantool> box.space.test:replace({1,2,3})
---
- [1, 2, 3]
...

tarantool> f = fiber.new(function() s:replace({2,2,3}) s:replace({3,2,3}) end)
---
...

tarantool> f:set_joinable(true)
---
...

tarantool> f:join()
---
- true
...

tarantool> box.space.test:truncate()
---
...

tarantool> box.rollback()
---
...

tarantool> collectgarbage()
Assertion failed: (!tuple->is_dirty), function tuple_unref, file /Users/o.babin/Projects/tarantool/src/box/tuple.h, line 1121.
[1]    68811 abort      ./src/tarantool
```

**Comment by ligurio** [comment]
reproduced with test `replication/qsync_random_leader.test.lua`
```
2020-12-02 22:20:38.325 [23033] main/253/console/unix/: I> set 'replication_synchro_timeout' configuration option to 0.01
2020-12-02 22:20:38.326 [23033] main/253/console/unix/: I> set 'replication_synchro_quorum' configuration option to 3
2020-12-02 22:20:38.480 [23033] main/263/console/unix/: I> set 'replication_synchro_timeout' configuration option to 1000
2020-12-02 22:20:38.480 [23033] main/263/console/unix/: I> set 'replication_synchro_quorum' configuration option to 6
tarantool: /builds/M4RrgQZ3/0/tarantool/tarantool/src/box/tuple.h:1121: void tuple_unref(tuple*): Assertion `!tuple->is_dirty' failed.
[131] sql-tap/tkt2640.test.lua                        memtx           [ pass ]
```
https://gitlab.com/tarantool/tarantool/-/jobs/887050437

**Comment by alyapunov** [comment]
Will be fixed in: create/alter space/index in transaction #600

**Comment by alyapunov** [comment]
We've fixed crashes, all other investigation will be done in create/alter space/index in transaction #600

**Comment by Korablev77** [comment]
Ok, there's remaining case when first TX creates space and second TX sees it meanwhile it is still not yet commited. I've moved it to #6138 since it will be closed in https://github.com/tarantool/tarantool/pull/6202
As @alyapunov said, crashes have been fixed so I guess we are able to close this issue.
