### ISSUE TITLE
Space name in duplicate key error

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#733]
Print space names along with index names in index errors. This is necessary to analyze broken replication.

**Comment by rtsisyk** [comment]
I fixed this problem couple weeks ago.

**Comment by kostja** [comment]
```
2015-02-25 15:53:45.006 [30942] main/103/replica/avi-cluster85.se.avit C> connected to 10.7.176.132:2202
2015-02-25 15:53:45.048 [30942] wal I> creating `/var/lib/tarantool/tarantool-ru-02/00000000000327431099.xlog.inprogress'
2015-02-25 15:53:45.528 [30942] main/103/replica/avi-cluster85.se.avit memtx_hash.cc:297 E> ER_TUPLE_FOUND: Duplicate key exists in unique index 'primary'
```

**Comment by kostja** [comment]
Space name is still missing, your change replaced index id with index name.

**Comment by rtsisyk** [comment]
OK!
