### ISSUE TITLE
Please update rpm repository metadata

### ISSUE THREAD

**Issue by x23n5902y** [tarantool/tarantool#7843]
**Bug description**

* OS: Linux
* OS Version: AlmaLinux 8 
* Architecture: amd64

**Steps to reproduce**
` reposync --repoid=tarantool_modules -p /var/tmp --download-metadata`

```
[MIRROR] tarantool-queue-0.0.1-1.el8.noarch.rpm: Status code: 404 for https://hb.bizmrg.com/tarantool_repo/release/modules/el/8/x86_64/Packages/tarantool-queue-0.0.1-1.el8.noarch.rpm (IP: 10.242.133.204)
[MIRROR] tarantool-queue-0.0.1-1.el8.noarch.rpm: Status code: 404 for https://hb.bizmrg.com/tarantool_repo/release/modules/el/8/x86_64/Packages/tarantool-queue-0.0.1-1.el8.noarch.rpm (IP: 10.242.133.204)
[MIRROR] tarantool-queue-0.0.1-1.el8.noarch.rpm: Status code: 404 for https://hb.bizmrg.com/tarantool_repo/release/modules/el/8/x86_64/Packages/tarantool-queue-0.0.1-1.el8.noarch.rpm (IP: 10.242.133.204)
[MIRROR] tarantool-queue-0.0.1-1.el8.noarch.rpm: Status code: 404 for https://hb.bizmrg.com/tarantool_repo/release/modules/el/8/x86_64/Packages/tarantool-queue-0.0.1-1.el8.noarch.rpm (IP: 10.242.133.204)
[FAILED] tarantool-queue-0.0.1-1.el8.noarch.rpm: No more mirrors to try - All mirrors were already tried without success
```

*Actual behavior**

**Expected behavior**

**Comment by x23n5902y** [comment]
any updates ?

**Comment by ylobankov** [comment]
@x23n5902y Please try again. It should be fixed now.

**Comment by x23n5902y** [comment]
Still can't sync repo using pull so i opened an issue in their project
Right now I'm getting a pull-specific error, but it only reproduces for the tarantool modules repo though
```
(pulp) [pulp@localhost ~]$ pulp rpm repository sync --name "tarantool-modules-el7-release" --remote "tarantool-modules-el7-release-remote"
Started background task /pulp/api/v3/tasks/b0b7e18a-126f-492a-90a7-884f0155b944/
..Error: Task /pulp/api/v3/tasks/b0b7e18a-126f-492a-90a7-884f0155b944/ failed: 'invalid input syntax for type numeric: ""
CONTEXT:  SQL statement "SELECT (select ROW(coalesce(NEW.epoch::numeric,0),
                          pulp_rpmver_array(coalesce(NEW.version,'pulp_isempty'))::pulp_evr_array_item[],
                          pulp_rpmver_array(coalesce(NEW.release,'pulp_isempty'))::pulp_evr_array_item[])::pulp_evr_t)"
PL/pgSQL function pulp_evr_trigger() line 3 at assignment

```
https://github.com/pulp/pulp_rpm/issues/2858

**Comment by ylobankov** [comment]
Looks like we fixed the issue from our side. At least I cannot see any problems now:

```console
ubuntu@ylobankov-ubuntu-20:~$ docker run -it --rm packpack/packpack:el-8
[root@c530859d03d5 /]# curl -L https://tarantool.io/kpPrBqS/release/2/installer.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0   4447      0 --:--:-- --:--:-- --:--:--  4447
100 11320  100 11320    0     0   9056      0  0:00:01  0:00:01 --:--:--     0
Detected operating system as centos/8.

################################
# Setting up yum repository... #
################################

#########################
# Cleaning yum cache... #
#########################
0 files removed

#################################
# Installing EPEL repository... #
#################################
CentOS Linux 8 - AppStream                                                                                                                                                   15 MB/s | 8.4 MB     00:00
CentOS Linux 8 - BaseOS                                                                                                                                                      11 MB/s | 4.6 MB     00:00
CentOS Linux 8 - Extras                                                                                                                                                      39 kB/s |  10 kB     00:00
CentOS Linux 8 - PowerTools                                                                                                                                                 6.1 MB/s | 2.3 MB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                              8.5 MB/s |  13 MB     00:01
Extra Packages for Enterprise Linux Modular 8 - x86_64                                                                                                                      449 kB/s | 733 kB     00:01
packpack_backports                                                                                                                                                           11 kB/s | 3.4 kB     00:00
packpack_backports-source                                                                                                                                                   5.6 kB/s | 1.1 kB     00:00
epel-release-latest-8.noarch.rpm                                                                                                                                             41 kB/s |  24 kB     00:00
Dependencies resolved.
============================================================================================================================================================================================================
 Package                                            Architecture                                 Version                                           Repository                                          Size
============================================================================================================================================================================================================
Upgrading:
 epel-release                                       noarch                                       8-18.el8                                          @commandline                                        24 k

Transaction Summary
============================================================================================================================================================================================================
Upgrade  1 Package

Total size: 24 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                    1/1
  Running scriptlet: epel-release-8-18.el8.noarch                                                                                                                                                       1/1
  Upgrading        : epel-release-8-18.el8.noarch                                                                                                                                                       1/2
  Running scriptlet: epel-release-8-18.el8.noarch                                                                                                                                                       1/2
  Cleanup          : epel-release-8-11.el8.noarch                                                                                                                                                       2/2
  Running scriptlet: epel-release-8-11.el8.noarch                                                                                                                                                       2/2
  Verifying        : epel-release-8-18.el8.noarch                                                                                                                                                       1/2
  Verifying        : epel-release-8-11.el8.noarch                                                                                                                                                       2/2

Upgraded:
  epel-release-8-18.el8.noarch

Complete!

#####################################
# Setting up tarantool EPEL repo... #
#####################################

########################
# Updating metadata... #
########################
EnterpriseLinux-8 - Tarantool                                                                                                                                               2.6 kB/s | 488  B     00:00
EnterpriseLinux-8 - Tarantool                                                                                                                                                84 kB/s | 2.8 kB     00:00
Importing GPG key 0xA773605B:
 Userid     : "Tarantool <admin@tarantool.org>"
 Fingerprint: 7CB1 C0EB 4776 404A CA67 DCAD C84B 9BCA A773 605B
 From       : https://download.tarantool.org/tarantool/release/series-2/gpgkey
EnterpriseLinux-8 - Tarantool                                                                                                                                                13 kB/s | 3.5 kB     00:00
EnterpriseLinux-8 - Tarantool                                                                                                                                               3.5 kB/s | 659  B     00:00
EnterpriseLinux-8 - Tarantool                                                                                                                                                22 kB/s | 2.4 kB     00:00
Importing GPG key 0xA795CA3A:
 Userid     : "Tarantool <support@tarantool.io>"
 Fingerprint: 6ACF 26A9 2E4E D97C 8BB9 0D45 EF12 8E21 A795 CA3A
 From       : https://download.tarantool.org/tarantool/modules/gpgkey
EnterpriseLinux-8 - Tarantool                                                                                                                                                29 kB/s |  11 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                               20 kB/s |  17 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64                                                                                                                              3.8 MB/s |  13 MB     00:03
Metadata cache created.

Tarantool 2 is ready to be installed by 'yum install -y tarantool'
[root@c530859d03d5 /]#
[root@c530859d03d5 /]# yum --showduplicates list tarantool-queue
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                       2.2 kB/s | 488  B     00:00
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                        74 kB/s | 2.8 kB     00:00
Importing GPG key 0xA773605B:
 Userid     : "Tarantool <admin@tarantool.org>"
 Fingerprint: 7CB1 C0EB 4776 404A CA67 DCAD C84B 9BCA A773 605B
 From       : https://download.tarantool.org/tarantool/release/series-2/gpgkey
Is this ok [y/N]: y
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                       3.3 kB/s | 1.3 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64 - Debug                                                                                                                      2.3 MB/s | 5.7 MB     00:02
Extra Packages for Enterprise Linux 8 - x86_64 - Source                                                                                                                     1.9 MB/s | 2.7 MB     00:01
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                       3.3 kB/s | 659  B     00:00
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                        21 kB/s | 2.4 kB     00:00
Importing GPG key 0xA795CA3A:
 Userid     : "Tarantool <support@tarantool.io>"
 Fingerprint: 6ACF 26A9 2E4E D97C 8BB9 0D45 EF12 8E21 A795 CA3A
 From       : https://download.tarantool.org/tarantool/modules/gpgkey
Is this ok [y/N]: y
EnterpriseLinux-8 - Tarantool Sources                                                                                                                                        10 kB/s | 3.5 kB     00:00
Available Packages
tarantool-queue.noarch                                                                        1.2.0.0-1.el8                                                                         tarantool_modules
tarantool-queue.src                                                                           1.2.0.0-1.el8                                                                         tarantool_modules-source
tarantool-queue.noarch                                                                        1.2.1.0-1.el8                                                                         tarantool_modules
tarantool-queue.src                                                                           1.2.1.0-1.el8                                                                         tarantool_modules-source
tarantool-queue.noarch                                                                        1.2.2.0-1.el8                                                                         tarantool_modules
tarantool-queue.src                                                                           1.2.2.0-1.el8                                                                         tarantool_modules-source
[root@c530859d03d5 /]#
```

Feel free to reopen if you have any issues with repo.

**Comment by Totktonada** [comment]
Fixed in pulp in https://github.com/pulp/pulp_rpm/pull/2866.
